main: awzaw\antispampro\AntiSpamPro
api: [2.0.0, 3.0.0-ALPHA1]
load: POSTWORLD
name: AntiSpamPro
description: "antispampro"
version: 1.0.8
author: awzaw
commands:
 asp:
  permission: asp
  default: op
  description: AntiSpamPro Commands
  usage: /asp [help]