main: awzaw\antispampro\AntiSpamPro
api: [2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4]
load: POSTWORLD
name: AntiSpamPro
description: "AntiSpamPro"
version: 1.2
author: awzaw
commands:
 asp:
  permission: asp
  default: op
  description: AntiSpamPro Commands
  usage: /asp [help]