main: awzaw\antispampro\AntiSpamPro
api:
- 1.14.0
- 2.0.0
load: STARTUP
name: AntiSpamPro
description: "antispampro"
version: 1.0.3
author: awzaw
commands:
 asp:
  permission: asp
  default: op
  description: AntiSpamPro Commands
  usage: /asp [help]
