main: awzaw\antispampro\AntiSpamPro
api: [2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
load: POSTWORLD
name: AntiSpamPro
description: "AntiSpamPro"
version: 1.3.3
author: awzaw
commands:
 asp:
  permission: asp.command
  description: "Change AntiSpamPro Settings"
  usage: "/asp [help || kick || ban || set <cooldown in secs)>]"
permissions:
  asp:
   default: op
   description: "Allows access to all ASP commands and bypass filter"
   children:
    asp.command:
     default: op
     description: "Allows access to all ASP commands"
    asp.bypass:
     default: op
     description: "Allows user to bypass ASP filter"