main: awzaw\antispampro\AntiSpamPro
api: [3.0.0]
load: POSTWORLD
name: AntiSpamPro
description: "antispampro"
version: 1.0.7
author: awzaw
commands:
 asp:
  permission: asp
  default: op
  description: AntiSpamPro Commands
  usage: /asp [help]