<?php

namespace awzaw\antispampro;

use pocketmine\plugin\PluginBase;

class ProfanityFilter extends PluginBase {

    public $plugin;

    const SEPARATOR_PLACEHOLDER = '{!!}';

    /**
     * Escaped separator characters
     */
    protected $escapedSeparatorCharacters = array(
        '\s',
    );

    /**
     * Unescaped separator characters.
     * @var array
     */
    protected $separatorCharacters = array(
        '@',
        '#',
        '%',
        '&',
        '_',
        ';',
        "'",
        '"',
        ',',
        '~',
        '`',
        '|',
        '!',
        '$',
        '^',
        '*',
        '(',
        ')',
        '-',
        '+',
        '=',
        '{',
        '}',
        '[',
        ']',
        ':',
        '<',
        '>',
        '?',
        '.',
        '/',
    );

    /**
     * List of potential character substitutions as a regular expression.
     *
     * @var array
     */
    protected $characterSubstitutions = array(
        '/a/' => array(
            'a',
            '4',
            '@',
            'Á',
            'á',
            'À',
            'Â',
            'à',
            'Â',
            'â',
            'Ä',
            'ä',
            'Ã',
            'ã',
            'Å',
            'å',
            'æ',
            'Æ',
            'α',
            'Δ',
            'Λ',
            'λ',
        ),
        '/b/' => array('b', '8', '\\', '3', 'ß', 'Β', 'β'),
        '/c/' => array('c', 'Ç', 'ç', 'ć', 'Ć', 'č', 'Č', '¢', '€', '<', '(', '{', '©'),
        '/d/' => array('d', '\\', ')', 'Þ', 'þ', 'Ð', 'ð'),
        '/e/' => array('e', '3', '€', 'È', 'è', 'É', 'é', 'Ê', 'ê', 'ë', 'Ë', 'ē', 'Ē', 'ė', 'Ė', 'ę', 'Ę', '∑'),
        '/f/' => array('f', 'ƒ'),
        '/g/' => array('g', '6', '9'),
        '/h/' => array('h', 'Η'),
        '/i/' => array('i', '!', '|', ']', '[', '1', '∫', 'Ì', 'Í', 'Î', 'Ï', 'ì', 'í', 'î', 'ï', 'ī', 'Ī', 'į', 'Į'),
        '/j/' => array('j'),
        '/k/' => array('k', 'Κ', 'κ'),
        '/l/' => array('l', '!', '|', ']', '[', '£', '∫', 'Ì', 'Í', 'Î', 'Ï', 'ł', 'Ł'),
        '/m/' => array('m'),
        '/n/' => array('n', 'η', 'Ν', 'Π', 'ñ', 'Ñ', 'ń', 'Ń'),
        '/o/' => array(
            'o',
            '0',
            'Ο',
            'ο',
            'Φ',
            '¤',
            '°',
            'ø',
            'ô',
            'Ô',
            'ö',
            'Ö',
            'ò',
            'Ò',
            'ó',
            'Ó',
            'œ',
            'Œ',
            'ø',
            'Ø',
            'ō',
            'Ō',
            'õ',
            'Õ',
        ),
        '/p/' => array('p', 'ρ', 'Ρ', '¶', 'þ'),
        '/q/' => array('q'),
        '/r/' => array('r', '®'),
        '/s/' => array('s', '5', '$', '§', 'ß', 'Ś', 'ś', 'Š', 'š'),
        '/t/' => array('t', 'Τ', 'τ'),
        '/u/' => array('u', 'υ', 'µ', 'û', 'ü', 'ù', 'ú', 'ū', 'Û', 'Ü', 'Ù', 'Ú', 'Ū'),
        '/v/' => array('v', 'υ', 'ν'),
        '/w/' => array('w', 'ω', 'ψ', 'Ψ'),
        '/x/' => array('x', 'Χ', 'χ'),
        '/y/' => array('y', '¥', 'γ', 'ÿ', 'ý', 'Ÿ', 'Ý'),
        '/z/' => array('z', 'Ζ', 'ž', 'Ž', 'ź', 'Ź', 'ż', 'Ż'),
    );

    /**
     * List of profanities to test against.
     *
     * @var array
     */
    protected $profanities = array();
    protected $separatorExpression;
    protected $characterExpressions;

    public function __construct(AntiSpamPro $plugin) {
        $this->plugin = $plugin;
        $config = $this->getBadWords();


        if (is_array($config)) {
            $this->profanities = $config;
        } else {
            $this->profanities = $this->loadProfanitiesFromFile($config);
        }

        $this->separatorExpression = $this->generateSeparatorExpression();
        $this->characterExpressions = $this->generateCharacterExpressions();
    }

    /**
     * Checks string for profanities based on list 'profanities'
     *
     * @param $string
     *
     * @return bool
     */
    public function hasProfanity($string) {
        if (empty($string)) {
            return false;
        }

        $profanities = array();
        $profanityCount = count($this->profanities);

        for ($i = 0; $i < $profanityCount; $i++) {
            $profanities[$i] = $this->generateProfanityExpression(
                    $this->profanities[$i], $this->characterExpressions, $this->separatorExpression
            );
        }

        foreach ($profanities as $profanity) {
            if ($this->stringHasProfanity($string, $profanity)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Obfuscates string that contains a 'profanity'.
     *
     * @param $string
     *
     * @return string
     */
    public function obfuscateIfProfane($string) {
        if ($this->hasProfanity($string)) {
            $string = str_repeat("*", strlen($string));
        }

        return $string;
    }

    /**
     * Generate a regular expression for a particular word
     *
     * @param $word
     * @param $characterExpressions
     * @param $separatorExpression
     *
     * @return mixed
     */
    protected function generateProfanityExpression($word, $characterExpressions, $separatorExpression) {
        $expression = '/' . preg_replace(
                        array_keys($characterExpressions), array_values($characterExpressions), $word
                ) . '/i';

        return str_replace(self::SEPARATOR_PLACEHOLDER, $separatorExpression, $expression);
    }

    /**
     * Checks a string against a profanity.
     *
     * @param $string
     * @param $profanity
     *
     * @return bool
     */
    private function stringHasProfanity($string, $profanity) {
        return preg_match($profanity, $string) === 1;
    }

    /**
     * Generates the separator regex to test characters in between letters.
     *
     * @param array  $characters
     * @param array  $escapedCharacters
     * @param string $quantifier
     *
     * @return string
     */
    private function generateEscapedExpression(
    array $characters = array(), array $escapedCharacters = array(), $quantifier = '*?'
    ) {
        $regex = $escapedCharacters;
        foreach ($characters as $character) {
            $regex[] = preg_quote($character, '/');
        }

        return '[' . implode('', $regex) . ']' . $quantifier;
    }

    /**
     * Generates the separator regular expression.
     *
     * @return string
     */
    private function generateSeparatorExpression() {
        return $this->generateEscapedExpression($this->separatorCharacters, $this->escapedSeparatorCharacters);
    }

    /**
     * Generates a list of regular expressions for each character substitution.
     *
     * @return array
     */
    protected function generateCharacterExpressions() {
        $characterExpressions = array();
        foreach ($this->characterSubstitutions as $character => $substitutions) {
            $characterExpressions[$character] = $this->generateEscapedExpression(
                            $substitutions, array(), '+?'
                    ) . self::SEPARATOR_PLACEHOLDER;
        }

        return $characterExpressions;
    }

    /**
     * Load 'profanities' from config file.
     *
     * @param $config
     *
     * @return array
     */
    private function loadProfanitiesFromFile($config) {
        /** @noinspection PhpIncludeInspection */
        return include($config);
    }

    private function getBadWords() {

        return array(
            'abortion',
            'abuser',
            'ahole',
            'alabama hotpocket',
            'alligatorbait',
            'anal',
            'analannie',
            'analsex',
            'anus',
            'areola',
            'arsebagger',
            'arsebandit',
            'arseblaster',
            'arsecowboy',
            'arsefuck',
            'arsefucker',
            'arsehat',
            'arsehole',
            'arseholes',
            'arsehore',
            'arsejockey',
            'arsekiss',
            'arsekisser',
            'arselick',
            'arselicker',
            'arselover',
            'arseman',
            'arsemonkey',
            'arsemunch',
            'arsemuncher',
            'arsepacker',
            'arsepirate',
            'arsepuppies',
            'arseranger',
            'arses',
            'arsewhore',
            'arsewipe',
            'assassinate',
            'assassination',
            'assbag',
            'assbagger',
            'assbandit',
            'assbanger',
            'assbite',
            'assblaster',
            'assclown',
            'asscock',
            'asscowboy',
            'asscracker',
            'assface',
            'assfuck',
            'assfucker',
            'assgoblin',
            'ass-hat',
            'asshat',
            'asshead',
            'asshole',
            'assholes',
            'assholz',
            'asshopper',
            'asshore',
            'ass-jabber',
            'assjacker',
            'assjockey',
            'asskiss',
            'asskisser',
            'assklown',
            'asslick',
            'asslicker',
            'asslover',
            'assman',
            'assmonkey',
            'ass monkey',
            'assmunch',
            'assmuncher',
            'assnigger',
            'asspacker',
            'ass-pirate',
            'asspirate',
            'asspuppies',
            'assranger',
            'assshit',
            'assshole',
            'asssucker',
            'asswad',
            'asswhore',
            'asswipe',
            'axwound',
            'azzhole',
            'backdoorman',
            'badfuck',
            'baldy',
            'ball licker',
            'balllicker',
            'ballsack',
            'bampot',
            'banging',
            'barelylegal',
            'barface',
            'barfface',
            'bassterds',
            'bastard',
            'bastards',
            'bastardz',
            'basterds',
            'basterdz',
            'bazongas',
            'bazooms',
            'beaner',
            'beastality',
            'beastial',
            'beastiality',
            'beat-off',
            'beatoff',
            'beatyourmeat',
            'bestial',
            'bestiality',
            'biatch',
            'bicurious',
            'bigass',
            'bigbastard',
            'bigbutt',
            'bitch',
            'bitchass',
            'bitcher',
            'bitches',
            'bitchez',
            'bitchin',
            'bitching',
            'bitchslap',
            'bitchtits',
            'bitchy',
            'biteme',
            'blackout',
            'blow job',
            'blowjob',
            'boffing',
            'bohunk',
            'bollick',
            'bollock',
            'bollocks',
            'bollox',
            'bondage',
            'boner',
            'boob',
            'boobies',
            'boobs',
            'booby',
            'bootycall',
            'bountybar',
            'breastjob',
            'breastlover',
            'breastman',
            'brothel',
            'brotherfucker',
            'bugger',
            'buggered',
            'buggery',
            'bukake',
            'bullcrap',
            'bulldike',
            'bulldyke',
            'bullshit',
            'bumblefuck',
            'bumfuck',
            'bungabunga',
            'bunghole',
            'butchbabes',
            'butchdike',
            'butchdyke',
            'butt-bang',
            'buttbang',
            'buttcheeks',
            'buttface',
            'butt-fuck',
            'buttfuck',
            'buttfucka',
            'butt-fucker',
            'buttfucker',
            'butt-fuckers',
            'buttfuckers',
            'butthead',
            'butthole',
            'buttman',
            'buttmunch',
            'buttmuncher',
            'butt-pirate',
            'buttpirate',
            'butt plug',
            'buttplug',
            'buttstain',
            'buttwipe',
            'byatch',
            'cacker',
            'cameljockey',
            'camel toe',
            'cameltoe',
            'carpet muncher',
            'carpetmuncher',
            'cawk',
            'cawks',
            'cherrypopper',
            'chesticle',
            'chickslick',
            'clamdigger',
            'clamdiver',
            'clit',
            'clitface',
            'clitfuck',
            'clitoris',
            'clogwog',
            'clunge',
            'clusterfuck',
            'cnts',
            'cntz',
            'cock',
            'cockass',
            'cockbite',
            'cockblock',
            'cockblocker',
            'cockburger',
            'cockcowboy',
            'cockface',
            'cockfight',
            'cockfucker',
            'cock-head',
            'cockhead',
            'cockjockey',
            'cockknob',
            'cockknoker',
            'cocklicker',
            'cocklover',
            'cockmaster',
            'cockmongler',
            'cockmongruel',
            'cockmonkey',
            'cockmuncher',
            'cocknob',
            'cocknose',
            'cocknugget',
            'cockqueen',
            'cockrider',
            'cocks',
            'cockshit',
            'cocksman',
            'cocksmith',
            'cocksmoke',
            'cocksmoker',
            'cocksniffer',
            'cocksucer',
            'cocksuck ',
            'cocksucked ',
            'cock-sucker',
            'cocksucker',
            'cocksucking',
            'cocktease',
            'cockwaffle',
            'cocky',
            'coitus',
            'commie',
            'condom',
            'coochie',
            'coochy',
            'coondog',
            'copulate',
            'cracker',
            'crackpipe',
            'crack-whore',
            'crackwhore',
            'crappy',
            'crotchjockey',
            'crotchmonkey',
            'crotchrot',
            'cum',
            'cumbubble',
            'cumdumpster',
            'cumfest',
            'cumguzzler',
            'cumjockey',
            'cumm',
            'cumquat',
            'cumqueen',
            'cumshot',
            'cumslut',
            'cumtart',
            'cunilingus',
            'cunillingus',
            'cunnie',
            'cunnilingus',
            'cunntt',
            'cunt',
            'cuntass',
            'cunteyed',
            'cuntface',
            'cuntfuck',
            'cuntfucker',
            'cunthole',
            'cuntlick ',
            'cuntlicker ',
            'cuntlicker',
            'cuntlicking ',
            'cuntrag',
            'cunts',
            'cuntslut',
            'cuntsucker',
            'cuntz',
            'cybersex',
            'cyberslimer',
            'dammit',
            'damn',
            'damnation',
            'damnit',
            'darkie',
            'darky',
            'datnigga',
            'deapthroat',
            'deepthroat',
            'defecate',
            'devilworshipper',
            'dick',
            'dickbag',
            'dickbeaters',
            'dickbrain',
            'dickface',
            'dickforbrains',
            'dickfuck',
            'dickfucker',
            'dickhead',
            'dickhole',
            'dickjuice',
            'dickless',
            'dicklick',
            'dicklicker',
            'dickmilk',
            'dickmonger',
            'dicks',
            'dickslap',
            'dick-sneeze',
            'dicksucker',
            'dicksucking',
            'dicktickler',
            'dickwad',
            'dickweasel',
            'dickweed',
            'dickwod',
            'dike',
            'dildo',
            'dildos',
            'dilldo',
            'dilldos',
            'dipshit',
            'dipstick',
            'dixiedike',
            'dixiedyke',
            'doggiestyle',
            'doggystyle',
            'dominatricks',
            'dominatrics',
            'dominatrix',
            'doochbag',
            'dookie',
            'douch',
            'douchbag',
            'douche',
            'douchebag',
            'douche-fag',
            'douchewaffle',
            'drag queen',
            'dragqueen',
            'dragqween',
            'dripdick',
            'dumass',
            'dumb ass',
            'dumbass',
            'dumbbitch',
            'dumbfuck',
            'dumbshit',
            'dumshit',
            'dyke',
            'easyslut',
            'eatballs',
            'eatme',
            'eatpussy',
            'ejaculate',
            'ejaculated',
            'ejaculating ',
            'ejaculation',
            'enema',
            'excrement',
            'executioner',
            'exhibitionist',
            'extremist',
            'facefucker',
            'facist',
            'faeces',
            'fagbag',
            'faget',
            'fagfucker',
            'fagging',
            'faggit',
            'faggot',
            'faggotcock',
            'faggots',
            'fagit',
            'fagot',
            'fagtard',
            'faigs',
            'fannyfucker',
            'farted ',
            'farting ',
            'farty ',
            'fastfuck',
            'fatass',
            'fatfuck',
            'fatfucker',
            'fatso',
            'feces',
            'felatio ',
            'felch',
            'felcher',
            'felching',
            'fellatio',
            'feltch',
            'feltcher',
            'feltching',
            'fetish',
            'fingerfuck ',
            'fingerfucked ',
            'fingerfucker ',
            'fingerfuckers',
            'fingerfucking ',
            'fister',
            'fistfuck',
            'fistfucked ',
            'fistfucker ',
            'fistfucking ',
            'fisting',
            'flamer',
            'flasher',
            'flatulence',
            'flid',
            'flipping the bird',
            'flyd',
            'flydie',
            'flydye',
            'fondle',
            'footaction',
            'footfuck',
            'footfucker',
            'footlicker',
            'foreskin',
            'fornicate',
            'foursome',
            'freakfuck',
            'freakyfucker',
            'freefuck',
            'fubar',
            'fuck',
            'fucka',
            'fuckable',
            'fuckass',
            'fuckbag',
            'fuckboy',
            'fuckbrain',
            'fuckbuddy',
            'fuckbutt',
            'fuckbutter',
            'fucked',
            'fuckedup',
            'fucker',
            'fuckers',
            'fuckersucker',
            'fuckface',
            'fuckfest',
            'fuckfreak',
            'fuckfriend',
            'fuckhead',
            'fuckher',
            'fuckhole',
            'fuckin',
            'fuckina',
            'fucking',
            'fuckingbitch',
            'fuckingcunt',
            'fuckinnuts',
            'fuckinright',
            'fuckit',
            'fuckknob',
            'fuckme ',
            'fuckmehard',
            'fuckmonkey',
            'fucknut',
            'fucknutt',
            'fuckoff',
            'fuckpig',
            'fucks',
            'fuckstick',
            'fucktard',
            'fucktart',
            'fuckup',
            'fuckwad',
            'fuckwhore',
            'fuckwit',
            'fuckwitt',
            'fuckyou',
            'fudge packer',
            'fudgepacker',
            'Fudge Packer',
            'fugly',
            'fuk',
            'Fukah',
            'Fuken',
            'fuker',
            'Fukin',
            'Fukk',
            'Fukkah',
            'Fukken',
            'Fukker',
            'Fukkin',
            'fuks',
            'funfuck',
            'fuuck',
            'gang bang',
            'gangbang',
            'gangbanged ',
            'gangbanger',
            'gatorbait',
            'gayass',
            'gaybob',
            'gayboy',
            'gaydo',
            'gayfuck',
            'gayfuckist',
            'gaygirl',
            'gaylord',
            'gaymuthafuckinwhore',
            'gaysex ',
            'gaytard',
            'gaywad',
            'gayz',
            'genital',
            'genitals',
            'getiton',
            'givehead',
            'glazeddonut',
            'godammit',
            'goddamit',
            'goddammit',
            'goddamn',
            'goddamned',
            'god-damned',
            'goddamnes',
            'goddamnit',
            'goddamnmuthafucker',
            'goldenshower',
            'gonorrehea',
            'gonzagas',
            'gooch',
            'gook',
            'gotohell',
            'greaseball',
            'gringo',
            'grostulation',
            'guido',
            'gypo',
            'gypp',
            'gyppie',
            'gyppo',
            'gyppy',
            'handjob',
            'hard on',
            'hardon',
            'hater',
            'headfuck',
            'herpes',
            'hijack',
            'hijacker',
            'hijacking',
            'hillbillies',
            'hindoo',
            'hitler',
            'holestuffer',
            'homobangers',
            'homodumbshit',
            'honger',
            'honkers',
            'honkey',
            'honky',
            'hookers',
            'hoore',
            'horney',
            'horniest',
            'horny',
            'horseshit',
            'hosejob',
            'hotdamn',
            'hotpussy',
            'hottotrot',
            'humping',
            'husky',
            'hymen',
            'iblowu',
            'incest',
            'insest',
            'intercourse',
            'internet wife',
            'interracial',
            'intheass',
            'inthebuff',
            'jackass',
            'jackoff',
            'jackshit',
            'jagoff',
            'japcrap',
            'japs',
            'jerkass',
            'jerk off',
            'jerk-off',
            'jerkoff',
            'jesuschrist',
            'jigaboo',
            'jiggabo',
            'jihad',
            'jijjiboo',
            'jisim',
            'jism',
            'jiss',
            'jizim',
            'jizjuice',
            'jizm ',
            'jizm',
            'jizz',
            'jizzim',
            'jizzum',
            'jubblies',
            'juggalo',
            'jungle bunny',
            'junglebunny',
            'kiddy fiddler',
            'kike',
            'kinky',
            'kissass',
            'knobz',
            'kondum',
            'kooch',
            'kootch',
            'krap',
            'krappy',
            'kraut',
            'kumbubble',
            'kumbullbe',
            'kummer',
            'kumming',
            'kums',
            'kunilingus',
            'kunnilingus',
            'kunt',
            'kunts',
            'kuntz',
            'kyke',
            'labia',
            'lactate',
            'lady boy',
            'ladyboy',
            'lameass',
            'lapdance',
            'lardass',
            'lesbain',
            'lesbayn',
            'lesbian',
            'lesbin',
            'lesbo',
            'lezbe',
            'lezbefriends',
            'lezbo',
            'lezz',
            'lezzer',
            'lezzie',
            'lezzo',
            'libido',
            'lickme',
            'limpdick',
            'lipshits',
            'lipshitz',
            'livesex',
            'lmfao',
            'loadedgun',
            'lovebone',
            'lovegoo',
            'lovegun',
            'lovejuice',
            'lovemuscle',
            'lovepistol',
            'loverocket',
            'low life',
            'lowlife',
            'lubejob',
            'lucifer',
            'luckycameltoe',
            'malicious',
            'manhater',
            'manpaste',
            'masochist',
            'masokist',
            'massterbait ',
            'masstrbait',
            'masstrbate',
            'mastabate',
            'mastabater',
            'masterbaiter',
            'masterbate',
            'master bates',
            'masterbates',
            'mastrabator',
            'masturbate',
            'masturbating',
            'mattressprincess',
            'mcfagget',
            'meatbeater',
            'meatrack',
            'mgger',
            'mggor',
            'milf',
            'minge',
            'mofo',
            'molest',
            'molestation',
            'molester',
            'molestor',
            'moneyshot',
            'mooncricket',
            'mothafuck',
            'mothafucka',
            'mothafuckaz',
            'mothafucked ',
            'mothafucker',
            'motha fucker',
            'mothafuckin',
            'mothafucking ',
            'mothafuckings',
            'motha fuker',
            'motha fukkah',
            'motha fukker',
            'motherfuck',
            'motherfucked',
            'mother-fucker',
            'motherfucker',
            'mother fucker',
            'motherfuckin',
            'motherfucking',
            'motherfuckings',
            'mother fukah',
            'mother fuker',
            'mother fukkah',
            'mother fukker',
            'motherlovebone',
            'muff',
            'muffdive',
            'muffdiver',
            'muffindiver',
            'mufflikcer',
            'muncher',
            'munging',
            'muthafucker',
            'mutha fucker',
            'mutha fukah',
            'mutha fuker',
            'mutha fukkah',
            'mutha fukker',
            'nastt',
            'nastybitch',
            'nastyho',
            'nastyslut',
            'nastywhore',
            'necro',
            'negro',
            'negroes',
            'negroid',
            'nigaboo',
            'nigga',
            'niggah',
            'niggaracci',
            'niggard',
            'niggarded',
            'niggarding',
            'niggardliness',
            'niggardliness\'s',
            'niggardly',
            'niggard\'s',
            'niggards',
            'niggaz',
            'nigger',
            'niggerhead',
            'niggerhole',
            'nigger\'s',
            'niggers',
            'niggle',
            'niggled',
            'niggles',
            'niggling',
            'nigglings',
            'niggor',
            'niggur',
            'niglet',
            'nignog',
            'nigr',
            'nigra',
            'nigre',
            'nigur',
            'niiger',
            'niigr',
            'nipple',
            'nipplering',
            'nittit',
            'nlgger',
            'nlggor',
            'nofuckingway',
            'nonce',
            'nookey',
            'nookie',
            'nudger',
            'nut case',
            'nutcase',
            'nutfucker',
            'nut sack',
            'nutsack',
            'ontherag',
            'orafis',
            'orgasim ',
            'orgasim',
            'orgasm',
            'orgasum',
            'orgies',
            'orgy',
            'oriface',
            'orifice',
            'orifiss',
            'packi',
            'packie',
            'packy',
            'paedo',
            'paedofile',
            'paedophile',
            'paki',
            'pakie',
            'paky',
            'palesimian',
            'panooch',
            'panti',
            'pearlnecklace',
            'pecker',
            'peckerhead',
            'peckerwood',
            'peedo',
            'peeenus',
            'peeenusss',
            'peehole',
            'peenus',
            'peinus',
            'penas',
            'penile',
            'penis',
            'penisbanger',
            'penis-breath',
            'penises',
            'penisfucker',
            'penispuffer',
            'penus',
            'penuus',
            'perv',
            'perversion',
            'pervert',
            'phonesex',
            'phuc',
            'phuck',
            'phuk',
            'phuked',
            'phuker',
            'phuking',
            'phukked',
            'phukker',
            'phukking',
            'phungky',
            'phuq',
            'pi55',
            'picaninny',
            'piccaninny',
            'pickaninny',
            'pikey',
            'piky',
            'pimper',
            'pimpjuic',
            'pimpjuice',
            'pimpsimp',
            'pindick',
            'piss',
            'pissed',
            'pissed off',
            'pisser',
            'pisses ',
            'pissflaps',
            'pisshead',
            'pissin ',
            'pissing',
            'pissoff ',
            'play boy',
            'playboy',
            'play bunny',
            'playbunny',
            'play girl',
            'playgirl',
            'plumper',
            'pocketpool',
            'polac',
            'polack',
            'polak',
            'polesmoker',
            'pollock',
            'poonani',
            'poonany',
            'poontang',
            'pooperscooper',
            'pooping',
            'poorwhitetrash',
            'poostabber',
            'popimp',
            'porch monkey',
            'porchmonkey',
            'porn',
            'pornflick',
            'pornking',
            'porno',
            'pornography',
            'pornprincess',
            'premature',
            'pric',
            'prick',
            'prik',
            'prickhead',
            'prostitute',
            'protestant',
            'pu55i',
            'pu55y',
            'pube',
            'pubiclice',
            'punanny',
            'punta',
            'puntang',
            'purinaprincess',
            'pusse',
            'pussee',
            'pussie',
            'pussies',
            'pussy',
            'pussyeater',
            'pussyfucker',
            'pussylicker',
            'pussylicking',
            'pussylips',
            'pussylover',
            'pussypounder',
            'pusy',
            'puuke',
            'puuker',
            'queef',
            'queer',
            'queerbait',
            'queerhole',
            'queers',
            'queerz',
            'quim',
            'qweers',
            'qweerz',
            'qweir',
            'rag head',
            'raghead',
            'raped',
            'rapist',
            'rearend',
            'rearentry',
            'recktum',
            'rectum',
            'redneck',
            'rentafuck',
            'retard',
            'retarded',
            'rimjob',
            'rimming',
            'robber',
            'ruski',
            'russki',
            'russkie',
            'sadist',
            'sadom',
            'saeema butt',
            'sandm',
            'sand nigger',
            'sandnigger',
            'scag',
            'scank',
            'schlong',
            'screwing',
            'screwyou',
            'scrote',
            'scrotum',
            'scumbag',
            'seaman staines',
            'semen',
            'sexed',
            'sexfarm',
            'sexhound',
            'sexhouse',
            'sexing',
            'sexkitten',
            'sexpot',
            'sexslave',
            'sextogo',
            'sextoy',
            'sextoys',
            'sexwhore',
            'sexymoma',
            'sexy-slim',
            'seymour butts',
            'shag',
            'shagger',
            'shaggin',
            'shagging',
            'shat',
            'shhit',
            'shit',
            'shitass',
            'shitbag',
            'shitbagger',
            'shitbrains',
            'shitbreath',
            'shitcan',
            'shitcanned',
            'shitcunt',
            'shitdick',
            'shite',
            'shiteater',
            'shited',
            'shiter',
            'shitface',
            'shitfaced',
            'shitfit',
            'shitforbrains',
            'shitfuck',
            'shitfucker',
            'shitfull',
            'shithapens',
            'shithappens',
            'shithead',
            'shithole',
            'shithouse',
            'shiting',
            'shitlist',
            'shitola',
            'shitoutofluck',
            'shits',
            'shitspitter',
            'shitstain',
            'shitted',
            'shitter',
            'shittiest',
            'shitting',
            'shitty',
            'shity',
            'shitz',
            'shiz',
            'shiznit',
            'shortfuck',
            'shyt',
            'shyte',
            'shytty',
            'shyty',
            'sissy',
            'sixsixsix',
            'sixtynine',
            'sixtyniner',
            'skanck',
            'skank',
            'skankbitch',
            'skankee',
            'skankey',
            'skankfuck',
            'skanks',
            'skankwhore',
            'skanky',
            'skankybitch',
            'skankywhore',
            'skeet',
            'skinflute',
            'skullfuck',
            'skum',
            'skumbag',
            'slanteye',
            'slantyeye',
            'slapper',
            'slavedriver',
            'sleezebag',
            'sleezeball',
            'slideitin',
            'slimeball',
            'slimebucket',
            'slopehead',
            'slopey',
            'slopy',
            'slut',
            'slutbag',
            'sluts',
            'slutt',
            'slutting',
            'slutty',
            'slutwear',
            'slutwhore',
            'slutz',
            'smackthemonkey',
            'smeg',
            'smut',
            'snatch',
            'snatchpatch',
            'snowback',
            'snownigger',
            'sodom',
            'sodomise',
            'sodomite',
            'sodomize',
            'sodomy',
            'son-of-a-bitch',
            'sonofabitch',
            'sonofbitch',
            'spacca',
            'spaghettibender',
            'spaghettinigger',
            'spank',
            'spankthemonkey',
            'spastic',
            'spazza',
            'sperm',
            'spermacide',
            'spermbag',
            'spermhearder',
            'spermherder',
            'spick',
            'spik',
            'spitter',
            'splittail',
            'splooge',
            'spooge',
            'spook',
            'spreadeagle',
            'spunk',
            'squaw',
            'stabber',
            'stiffy',
            'strapon',
            'stripclub',
            'stripper',
            'stroking',
            'stupidfuck',
            'stupidfucker',
            'suckass',
            'suckdick',
            'sucker',
            'suckme',
            'suckmyass',
            'suckmydick',
            'suckmytit',
            'suckoff',
            'swallower',
            'swastika',
            'syphilis',
            'tampon',
            'tantra',
            'tarbaby',
            'testicle',
            'testicles',
            'thai bride',
            'thick as',
            'thicklips',
            'thicko',
            'thirdeye',
            'thirdleg',
            'threesome',
            'thundercunt',
            'timbernigger',
            'titbitnipply',
            'titfuck',
            'titfucker',
            'titfuckin',
            'titjob',
            'titlicker',
            'titlover',
            'tittie',
            'titties',
            'titty',
            'tittyfuck',
            'tonguethrust',
            'tonguethruster',
            'tonguetramp',
            'torture',
            'tosser',
            'tosspot',
            'towel head',
            'towelhead',
            'trailertrash',
            'trannie',
            'tranny',
            'transvestite',
            'trisexual',
            'trouser snake',
            'tuckahoe',
            'tunneloflove',
            'turnon',
            'twat',
            'twatlips',
            'twats',
            'twatwaffle',
            'twinkie',
            'twobitwhore',
            'unclefucker',
            'unfuckable',
            'upskirt',
            'uptheass',
            'upthebutt',
            'urinate',
            'uterus',
            'vagiina',
            'vagina',
            'vaginal',
            'vajayjay',
            'vajina',
            'va-j-j',
            'valjina',
            'vibrater',
            'vibrator',
            'vietcong',
            'violate',
            'violation',
            'virginbreaker',
            'vjayjay',
            'vullva',
            'vulva',
            'wank',
            'wanker',
            'wanking',
            'wankjob',
            'waysted',
            'welcher',
            'wetback',
            'wetspot',
            'whacker',
            'whigger',
            'whiskeydick',
            'whiskydick',
            'whitenigger',
            'whitetrash',
            'whitey',
            'whoor',
            'whore',
            'whorebag',
            'whoreface',
            'whorefucker',
            'whorehouse',
            'wife beater',
            'williewanker',
            'wuzzie',
            'x-rated',
            'xrated',
            'yellowman',
            'zigabo',
            'zipperhea',
            'zipper head'
        );
    }

}
